// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fhjjwysajmvghthnuvfk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZoamp3eXNham12Z2h0aG51dmZrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY5MzgwNjcsImV4cCI6MjA3MjUxNDA2N30.OLOIzpkUhpoosiVUS7QGGKn22Y4hmIJn0DCrcdYcdmQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});